name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'cardinal-patches_nooneknows.zip'
        exclusions: '*.git* *.github*'

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag_name: "release-${{ github.run_number }}"
        artifacts: "cardinal-patches_nooneknows.zip"
        token: ${{ secrets.CARDINAL_PATCHES_RELEASE }}
