name: Create and Upload Zip to Release

on:
  push:
    branches:
      - main # Run workflow on push to main branch
    tags:
      - '*'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  checks: write

  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  release-zip:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'cardinal-patches_nooneknows_v${{ github.run_number }}.zip'
        exclusions: '*.git* /*.github*/'

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "cardinal-patches_nooneknows_v${{ github.run_number }}.zip"
        tag: ${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
