
name: Create and Upload Zip to Release

on:
  push:
    branches:
      - main # Run workflow on push to main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create and Upload Zip to Release
      uses: montudor/action-zip-release@v0.1.0
      with:
        tag_name: release-${{ github.run_number }} 
        release_name: Cardinal-Patches_nooneknows
        zip_name: cardinal-patches_nooneknows.zip
        args: |
          -x ".git/*" # Exclude specific folders
          -x ".github/*"
      env:
        GITHUB_TOKEN: ${{ secrets.CARDINAL_PATCHES_RELEASE }}
