name: Create and Upload Zip to Release

on:
  push:
    branches:
      - main # Run workflow on push to main branch
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  contents: write
  checks: write

  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  release-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Zip repository (excluding specific folders)
      run: |
        zip -r cardinal-patches_nooneknows.zip ./* -x ".git/*" ".github/*"

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "cardinal-patches_nooneknows.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
